//
// Wire
// Copyright (C) 2026 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

import Foundation

// sourcery: AutoMockable
public protocol MLSAPI {

    /// Fetch the info of MLS support on the backend available from ``APIVersion`` v5.

    func getBackendMLSPublicKeys() async throws -> BackendMLSPublicKeys

    /// Post a commit bundle.
    ///
    /// - Parameter bundle: commit bundle to post
    /// - Returns: updates events generated by the commit
    ///
    /// Available from ``APIVersion`` v5.
    ///

    func postCommitBundle(_ bundle: CommitBundle) async throws -> [UpdateEvent]

    /// Upload MLS key packages for a client.
    ///
    /// - Parameters:
    ///   - clientID: The client ID to upload key packages for.
    ///   - keyPackages: The key packages to upload.
    ///
    /// Available from ``APIVersion`` v5.
    ///

    func uploadKeyPackages(clientID: String, keyPackages: KeyPackageUpload) async throws

    /// Reset an MLS Conversation to epoch 0
    /// - Parameters:
    ///   - epoch: current epoch
    ///   - groupID: MLS group id of the conversation
    ///
    /// Available from ``APIVersion`` v9.
    ///

    func resetMLSConversation(epoch: UInt64, groupID: String) async throws
}
