version: 2
updates:
  - package-ecosystem: "swift"
    directory: "/wire-ios-mono.xcworkspace/xcshareddata/swiftpm"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
