//
// Wire
// Copyright (C) 2026 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

public import Foundation
public import WireMessagingDomain

/// Hand-written mock for ``WireDriveFetchNodeUseCaseProtocol``.
///
/// This mock is deliberately **not** generated by AutoMockable (the protocol has no
/// `// sourcery: AutoMockable` annotation). `WireDriveFetchNodeUseCaseProtocol` is `Sendable` and
/// `MessageReplyAttachmentsViewModel.latestVisibleAttachments` calls `invoke(nodeID:)` concurrently
/// — one `TaskGroup` child task per attachment. The AutoMockable-generated mock is marked
/// `@unchecked Sendable` but records invocations by appending to a plain array without
/// synchronisation, so those concurrent calls race on the array and crash. This version serialises
/// the invocation recording behind a lock.
///
/// The public surface mirrors what AutoMockable would generate (`invokeNodeID_Invocations`,
/// `invokeNodeID_MockError`, `invokeNodeID_MockMethod`, `invokeNodeID_MockValue`) so it stays a
/// drop-in replacement for existing call sites.
public final class MockWireDriveFetchNodeUseCaseProtocol: WireDriveFetchNodeUseCaseProtocol, @unchecked Sendable {

    public init() {}

    // MARK: - invoke

    private let lock = NSLock()
    private var _invokeNodeID_Invocations: [UUID] = []

    public var invokeNodeID_Invocations: [UUID] {
        get {
            lock.lock()
            defer { lock.unlock() }
            return _invokeNodeID_Invocations
        }
        set {
            lock.lock()
            defer { lock.unlock() }
            _invokeNodeID_Invocations = newValue
        }
    }

    public var invokeNodeID_MockError: Error?
    public var invokeNodeID_MockMethod: ((UUID) async throws -> WireDriveNode?)?
    public var invokeNodeID_MockValue: WireDriveNode??

    public func invoke(nodeID: UUID) async throws -> WireDriveNode? {
        // Record in a synchronous helper: `NSLock.lock()/unlock()` are unavailable directly in an
        // async context, and the recording never spans a suspension point anyway.
        record(invocation: nodeID)

        if let error = invokeNodeID_MockError {
            throw error
        }

        if let mock = invokeNodeID_MockMethod {
            return try await mock(nodeID)
        } else if let mock = invokeNodeID_MockValue {
            return mock
        } else {
            fatalError("no mock for `invokeNodeID`")
        }
    }

    private func record(invocation nodeID: UUID) {
        lock.lock()
        defer { lock.unlock() }
        _invokeNodeID_Invocations.append(nodeID)
    }
}
