macos_instance:
  image: ghcr.io/cirruslabs/macos-ventura-xcode:14.2

task:
  script: 
  - brew install carthage
  - sh ./setup.sh
  - echo "Building WireSystem..."
  - xcodebuild clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -workspace wire-ios-mono.xcworkspace -scheme Wire-iOS -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2'
