# Documentation https://github.com/mono0926/LicensePlist

options:
  outputPath: ./wire-ios/Wire-iOS/Resources/Settings.bundle
  cartfilePath: Cartfile
  force: true
  addVersionNumbers: true
  suppressOpeningDirectory: true
  # failIfMissingLicense: true
  sandboxMode: true
  packageSourcesPath: TestDownload