options:
  outputPath: "./com.mono0926.LicensePlist.Output"
  cartfilePath: Cartfile
  # packagePaths:
  #   - scripts/Package.swift
  # packageSourcesPath: "./SourcePackages"
  xcworkspacePath: "*.xcworkspace"
  prefix: Licenses
  # gitHubToken: YOUR_GITHUB_TOKEN
  force: true
  addVersionNumbers: true
  htmlPath: licenses.html
  suppressOpeningDirectory: true
  # failIfMissingLicense: true
  sandboxMode: false