disabled_rules:
    - function_body_length
    - type_body_length
    - file_length
    - generic_type_name
    - force_cast
    - force_try
    - identifier_name
    - type_name
    - todo
    - large_tuple
    - unused_setter_value
    - notification_center_detachment
    - discarded_notification_center_observer
    - cyclomatic_complexity
    - closure_parameter_position
    - statement_position
    - weak_delegate
    - inclusive_language
    - class_delegate_protocol
    - legacy_cggeometry_functions
    - legacy_constructor
    - legacy_hashing
    - multiple_closures_with_trailing_closure
    - nesting
    - function_parameter_count
    - xctfail_message
    - reduce_boolean
    - shorthand_operator
    
included:
    - Sources
    - Tests


# In order to deal with the huge number of violations, first set
# very high limits then iteratively reduce the limits and resolve
# the few violations. Repeat this until we find suitable limits.

line_length:
    warning: 250
    error: 250
