disabled_rules:
    - function_body_length
    - type_body_length
    - file_length
    - generic_type_name
    - force_cast
    - force_try
    - identifier_name
    - type_name
    - todo
    - large_tuple
    - unused_setter_value
    - cyclomatic_complexity
    - weak_delegate
    - inclusive_language
    - class_delegate_protocol
    - nesting
    - function_parameter_count
    - notification_center_detachment
    - discarded_notification_center_observer
    - xctfail_message
    - compiler_protocol_init
    - no_fallthrough_only

excluded:
    - sourcery
    - fastlane
    - Carthage
    - DerivedData
    - vendor
    - wire-ios/Templates
    - "wire-ios/Wire-iOS/Generated/Assets+Generated.swift"
    - "wire-ios/Wire-iOS/Generated/Strings+Generated.swift"
    - "wire-ios/Wire-iOS Share Extension/Generated/Strings+Generated.swift"
    - "wire-ios-protos/Protos/messages.pb.swift"
    - "wire-ios-protos/Protos/mls.pb.swift"
    - "wire-ios-protos/Protos/otr.pb.swift"
    - "wire-ios-data-model/Support/Sourcery/generated/AutoMockable.generated.swift"
    - "wire-ios-sync-engine/sourcery/generated/AutoMockable.generated.swift"
    - "wire-ios-sync-engine/sourcery/generated/AutoMockable.manual.swift"
    - "wire-ios-request-strategy/sourcery/generated/AutoMockable.generated.swift"
    - "wire-ios/WireCommonComponents/Icons/Autogenerated/StyleKitIcons.generated.swift"

# In order to deal with the huge number of violations, first set
# very high limits then iteratively reduce the limits and resolve
# the few violations. Repeat this until we find suitable limits.

line_length:
    warning: 500
    error: 500

swiftlint_version: 0.53.0
