disabled_rules:
    - function_body_length
    - type_body_length
    - file_length
    - generic_type_name
    - force_cast
    - force_try
    - identifier_name
    - type_name
    - todo
    - large_tuple
    - unused_setter_value
    - cyclomatic_complexity
    - weak_delegate
    - inclusive_language
    - class_delegate_protocol
    - nesting
    - function_parameter_count
    - notification_center_detachment
    - discarded_notification_center_observer
    - closure_parameter_position
    - statement_position
    - multiple_closures_with_trailing_closure
    - xctfail_message
    - compiler_protocol_init
    - reduce_boolean
    - legacy_cggeometry_functions
    - legacy_constructor
    - legacy_hashing

excluded:
    - sourcery
    - fastlane
    - Carthage
    - vendor
    - wire-ios/Templates
    - "**/*.pb.swift"
    - "**/*.generated.swift"
    - "**/*+Generated.swift"

# In order to deal with the huge number of violations, first set
# very high limits then iteratively reduce the limits and resolve
# the few violations. Repeat this until we find suitable limits.

line_length:
    warning: 500
    error: 500
