# Credentials.

"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_API_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

# Preserve file structure on Crowdin.

"preserve_hierarchy": true

# Specify which source files to upload and where to store their
# downloaded translation.

files: [
 {
  "source" : "/wire-ios/Wire-iOS/Resources/Base.lproj/Localizable.strings",
  "dest" : "/App/Wire-iOS/Resources/Localizable.strings",
  "translation" : "/wire-ios/Wire-iOS/Resources/%osx_code%/%original_file_name%",
 },
 {
  "source" : "/wire-ios/Wire-iOS/Resources/Base.lproj/Accessibility.strings",
  "dest" : "/App/Wire-iOS/Resources/Accessibility.strings",
  "translation" : "/wire-ios/Wire-iOS/Resources/%osx_code%/%original_file_name%",
 },
 {
  "source" : "/wire-ios/Wire-iOS/Resources/Base.lproj/Localizable.stringsdict",
  "dest" : "/App/Wire-iOS/Resources/Localizable.stringsdict",
  "translation" : "/wire-ios/Wire-iOS/Resources/%osx_code%/%original_file_name%",
 },
 {
  "source" : "/wire-ios/Wire-iOS/Resources/Base.lproj/InfoPlist.strings",
  "dest" : "/App/Wire-iOS/Resources/InfoPlist.strings",
  "translation" : "/wire-ios/Wire-iOS/Resources/%osx_code%/%original_file_name%",
 },
 {
  "source" : "/wire-ios/Wire-iOS Share Extension/Resources/Base.lproj/Localizable.strings",
  "dest" : "/App/Wire-iOS Share Extension/Localizable.strings",
  "translation" : "/wire-ios/Wire-iOS Share Extension/%osx_code%/%original_file_name%",
 },
 {
  "source" : "/WireUI/Sources/WireSidebarUI/Resources/en.lproj/Localizable.strings",
  "dest" : "/App/WireSidebarUI/Resources/Localizable.strings",
  "translation" : "/WireUI/Sources/WireSidebarUI/Resources/%osx_code%/%original_file_name%",
 },
 {
  "source" : "/WireUI/Sources/WireMainNavigationUI/Resources/Localizable.xcstrings",
  "dest" : "/App/WireMainNavigationUI/Resources/Localizable.xcstrings",
  "translation" : "%original_path%/%original_file_name%",
  "multilingual": true,
 },
{
  "source" : "/WireUI/Sources/WireMainNavigationUI/Resources/Accessibility.xcstrings",
  "dest" : "/App/WireMainNavigationUI/Resources/Accessibility.xcstrings",
  "translation" : "%original_path%/%original_file_name%",
  "multilingual": true,
 },
]
