# Credentials.

"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env" : "CROWDIN_API_TOKEN"
"base_path" : "."
"base_url" : "https://api.crowdin.com"

# Preserve file structure on Crowdin.

"preserve_hierarchy": true

# Specify which source files to upload and where to store their
# downloaded translation.

files: [
  {
    "source" : "/wire-ios/Wire-iOS/Resources/Localization/Base.lproj/Localizable.strings",
    "dest" : "/App/Wire-iOS/Resources/Localizable.strings",
    "translation" : "/wire-ios/Wire-iOS/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/wire-ios/Wire-iOS/Resources/Localization/Base.lproj/Accessibility.strings",
    "dest" : "/App/Wire-iOS/Resources/Accessibility.strings",
    "translation" : "/wire-ios/Wire-iOS/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/wire-ios/Wire-iOS/Resources/Localization/Base.lproj/Localizable.stringsdict",
    "dest" : "/App/Wire-iOS/Resources/Localizable.stringsdict",
    "translation" : "/wire-ios/Wire-iOS/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/wire-ios/Wire-iOS/Resources/Localization/Base.lproj/InfoPlist.strings",
    "dest" : "/App/Wire-iOS/Resources/InfoPlist.strings",
    "translation" : "/wire-ios/Wire-iOS/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/wire-ios/Wire-iOS Share Extension/Resources/Localization/Base.lproj/Localizable.strings",
    "dest" : "/App/Wire-iOS Share Extension/Localizable.strings",
    "translation" : "/wire-ios/Wire-iOS Share Extension/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireUI/Sources/WireSidebarUI/Resources/Localization/en.lproj/Localizable.strings",
    "dest" : "/App/WireSidebarUI/Resources/Localization/Localizable.strings",
    "translation" : "/WireUI/Sources/WireSidebarUI/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireUI/Sources/WireSidebarUI/Resources/Localization/en.lproj/Accessibility.strings",
    "dest" : "/App/WireSidebarUI/Resources/Localization/Accessibility.strings",
    "translation" : "/WireUI/Sources/WireSidebarUI/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireAuthentication/Sources/WireAuthenticationUI/Resources/Localization/en.lproj/Accessibility.strings",
    "dest" : "/App/WireAuthenticationUI/Resources/Localization/Accessibility.strings",
    "translation" : "/WireAuthentication/Sources/WireAuthenticationUI/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireAuthentication/Sources/WireAuthenticationUI/Resources/Localization/en.lproj/Localizable.strings",
    "dest" : "/App/WireAuthenticationUI/Resources/Localization/Localizable.strings",
    "translation" : "/WireAuthentication/Sources/WireAuthenticationUI/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireUI/Sources/WireMainNavigationUI/Resources/Localization/Localizable.xcstrings",
    "dest" : "/App/WireMainNavigationUI/Resources/Localization/Localizable.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireMainNavigationUI/Resources/Localization/Accessibility.xcstrings",
    "dest" : "/App/WireMainNavigationUI/Resources/Localization/Accessibility.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireFolderPickerUI/Resources/Localization/Localizable.xcstrings",
    "dest" : "/App/WireFolderPickerUI/Resources/Localization/Localizable.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireFolderPickerUI/Resources/Localization/Accessibility.xcstrings",
    "dest" : "/App/WireFolderPickerUI/Resources/Localization/Accessibility.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireIndividualToTeamMigrationUI/Resources/Localization/Localizable.xcstrings",
    "dest" : "/App/WireIndividualToTeamMigrationUI/Resources/Localization/Localizable.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireIndividualToTeamMigrationUI/Resources/Localization/Accessibility.xcstrings",
    "dest" : "/App/WireIndividualToTeamMigrationUI/Resources/Localization/Accessibility.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireMoveToFolderUI/Resources/Localization/Localizable.xcstrings",
    "dest" : "/App/WireMoveToFolderUI/Resources/Localization/Localizable.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireMoveToFolderUI/Resources/Localization/Accessibility.xcstrings",
    "dest" : "/App/WireMoveToFolderUI/Resources/Localization/Accessibility.xcstrings",
    "translation" : "%original_path%/%original_file_name%",
    "multilingual": true,
  },
  {
    "source" : "/WireUI/Sources/WireReusableUIComponents/Resources/Localization/en.lproj/Localizable.strings",
    "dest" : "/App/WireReusableUIComponents/Resources/Localization/Localizable.strings",
    "translation" : "/WireUI/Sources/WireReusableUIComponents/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireUI/Sources/WireSettingsUI/Resources/Localization/en.lproj/Accessibility.strings",
    "dest" : "/App/WireSettingsUI/Resources/Localization/Accessibility.strings",
    "translation" : "/WireUI/Sources/WireSettingsUI/Resources/Localization/%osx_code%/%original_file_name%",
  },
  {
    "source" : "/WireUI/Sources/WireSettingsUI/Resources/Localization/en.lproj/Localizable.strings",
    "dest" : "/App/WireSettingsUI/Resources/Localization/Localizable.strings",
    "translation" : "/WireUI/Sources/WireSettingsUI/Resources/Localization/%osx_code%/%original_file_name%",
  }
]
