sources:
  - ../Source
  - ../CoreCrypto
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableTestableImports: ["WireDataModel"]
  autoMockableImports: ["LocalAuthentication"]
 
