sources:
  - ../../WireDomain
templates:
  - ./LegacyAutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["WireAPI", "WireDataModel", "WireDomainPackage"]
  autoMockableTestableImports: ["WireDomain"]
