sources:
  - ../../WireDomain
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["GenericMessageProtocol", "WireNetwork", "WireDataModel", "WireDomainPackage", "WireCoreCrypto", "Combine", "WireCallingDomain"]
  autoMockableTestableImports: ["WireDomain"]
