name: "Add Allure report"

inputs:
  xcresult_search_path:
    required: false
    default: "artifacts"
  allure_artifact_name:
    required: false
    default: "html-report-${{ github.run_number }}"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      if: always()
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 20
        package-manager-cache: false

    - name: Generate Allure Report
      if: always()
      shell: bash
      env:
        XCRESULT_SEARCH_PATH: ${{ inputs.xcresult_search_path }}
      run: bash ./scripts/run-generate-allure-report.sh "$XCRESULT_SEARCH_PATH"
        
    - name: Upload Allure Report Artifact
      if: ${{ env.ALLURE_REPORT_AVAILABLE == 'true' }}
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ${{ inputs.allure_artifact_name }}
        path: allure-reports/

    - name: Patch Allure link into the Test Results comment
      if: always()
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
        ALLURE_ARTIFACT_NAME: ${{ inputs.allure_artifact_name }}
      run: bash ./scripts/run-update-comment.sh "Test Results" "$ALLURE_ARTIFACT_NAME"
