#!/bin/bash -e

if [ $IS_INTERNAL_BUILD == '1' ]; then
    for(( i=0; i < $SCRIPT_INPUT_FILE_COUNT; i++ )); do
        INPUT_FILE="SCRIPT_INPUT_FILE_$i"
        echo "Copying internal build file: ${!INPUT_FILE}"
        cp -Ra "${!INPUT_FILE}" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/"
    done
fi
