//
// Wire
// Copyright (C) 2024 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

import Foundation
import PackagePlugin

//@main
//struct SwiftGenPlugin: BuildToolPlugin {
//    func createBuildCommands(
//        context: PluginContext,
//        target: Target
//    ) throws -> [Command] {
//
//        let tool = try context.tool(named: "swiftgen")
//        return [
//            .prebuildCommand(
//                displayName: "Running \(tool)",
//                executable: .init(tool.path.string),
//                arguments: ["--help"],
//                outputFilesDirectory: context.pluginWorkDirectory
//            )
//        ]
//
//        let u = target.directory
//            .removingLastComponent()
//            .removingLastComponent()
//            .removingLastComponent()
//            .appending("scripts")
//            .string
//
//        let v = target.directory.appending("swiftgen.yml")
//
//
//        // Define the directory for generated sources
//        let generatedSourcesDir = context.pluginWorkDirectory.appending("SwiftGenPlugin")
//        try FileManager.default.createDirectory(
//            atPath: generatedSourcesDir.string,
//            withIntermediateDirectories: true
//        )
//
//        // Path to the generated Swift file
//        let outputFile = "SnapshotTestReferenceImageDirectory_.swift"
//
//        // The directory variable to generate
//        let directory = target.directory.appending(["Resources", "ReferenceImages"])
//
//        // Contents of the generated Swift file
//        let contents = """
//        // This file is generated by SwiftGenPlugin.
//        //public let SnapshotTestReferenceImageDirectory = "\(directory)"
//        """ + "\n"
//
//        // Write the contents to the generated Swift file
//        try contents.write(
//            to: URL(fileURLWithPath: generatedSourcesDir.appending(outputFile).string),
//            atomically: true,
//            encoding: .utf8
//        )
//
//        return [
//            // We actually just want to inform the build system about the genrated fileusing the
//            // `outputFilesDirectory` argument. The executable with the provided arguments does nothing.
//            .prebuildCommand(
//                displayName: "Generating \(outputFile)",
//                executable: .init("/bin/zsh"),
//                arguments: ["-c", "\"\(u)/run-swiftgen.sh\" --config \"\(v)\""],
//                outputFilesDirectory: generatedSourcesDir
//            )
//        ]
//    }
//}


@main
struct SwiftGenPlugin: BuildToolPlugin {
    /// Entry point for creating build commands for targets in Swift packages.
    func createBuildCommands(context: PluginContext, target: Target) async throws -> [Command] {

        target.directory
        let tool = try context.tool(named: "swiftgen")
        return [
            .prebuildCommand(
                displayName: "Running \(tool)",
                executable: .init(tool.path.string),
                arguments: [],
                outputFilesDirectory: context.pluginWorkDirectory
            )
        ]


        // This plugin only runs for package targets that can have source files.
        guard let sourceFiles = target.sourceModule?.sourceFiles else { return [] }

        // Find the code generator tool to run (replace this with the actual one).
        let generatorTool = try context.tool(named: "my-code-generator")

        // Construct a build command for each source file with a particular suffix.
        return sourceFiles.map(\.path).compactMap {
            createBuildCommand(for: $0, in: context.pluginWorkDirectory, with: generatorTool.path)
        }
    }
}

extension SwiftGenPlugin {
    /// Shared function that returns a configured build command if the input files is one that should be processed.
    func createBuildCommand(for inputPath: Path, in outputDirectoryPath: Path, with generatorToolPath: Path) -> Command? {
        // Skip any file that doesn't have the extension we're looking for (replace this with the actual one).
        guard inputPath.extension == "my-input-suffix" else { return .none }

        // Return a command that will run during the build to generate the output file.
        let inputName = inputPath.lastComponent
        let outputName = inputPath.stem + ".swift"
        let outputPath = outputDirectoryPath.appending(outputName)
        return .buildCommand(
            displayName: "Generating \(outputName) from \(inputName)",
            executable: generatorToolPath,
            arguments: ["\(inputPath)", "-o", "\(outputPath)"],
            inputFiles: [inputPath],
            outputFiles: [outputPath]
        )
    }
}
