instanceCreationTimeoutInSeconds: 60
instanceMaximumRuntimeInMinutes: 10
instanceCleanupPeriodInMinutes: 5

server:
  applicationConnectors:
    - type: http
      port: 8080
      bindHost: 0.0.0.0

swagger:
  resourcePackage: com.wire.kalium.testservice.api.v1
  title: Kalium Testservice
  version: "1.0"

logging:
  level: INFO
  loggers:
    com.wire.kalium: INFO
  appenders:
    - type: console
      threshold: INFO
