sources:
  - ../../../WireFoundation/Sources/WireSystem
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["Foundation"]
  autoMockableTestableImports: ["WireSystem"]
