opt_out_usage
default_platform(:ios)

platform :ios do

    desc "Fetch dependencies"
    lane :prepare do
        sh "cd .. && ./setup.sh"
    end


    desc "Build for testing"
    lane :build do
        scan(
            scheme: "Wire-iOS",
            configuration: "Debug",
            build_for_testing: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            derived_data_path: "DerivedData",
            buildlog_path: "build",
            output_directory: "build",
            output_types: "junit"
        )
    end

    desc "Test without building"
    lane :test do
        scan(
            scheme: "Wire-iOS",
            configuration: "Debug",
            test_without_building: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            derived_data_path: "DerivedData",
            buildlog_path: "test",
            output_directory: "test",
            output_types: "junit"
        )
    end

    desc "Run post-test tasks"
    lane :post_test do
        sh "curl -s https://codecov.io/bash > codecov"
        sh "chmod +x codecov"
        codecov = "./codecov -J '^Wire$' -D ../DerivedData"

        if ENV["BUILD_REASON"] == "PullRequest"
            if ENV["CODECOV_TOKEN"].nil?
                UI.user_error! "codecov.io token missing for current repository. Set it in CODECOV_TOKEN environment variable"
            end

            if ENV["BUILD_SOURCEBRANCH"].nil?
                UI.user_error! "Source branch env variable missing. Set BUILD_SOURCEBRANCH to fix it"
            end

            pull_request_number = ENV["BUILD_SOURCEBRANCH"].split("/")[2] # For PRs the branch is in format "refs/pull/1/merge"

            codecov << " -t #{ENV["CODECOV_TOKEN"]} -P #{pull_request_number}"
        end

        sh codecov

    end
end
