opt_out_usage
default_platform(:ios)

platform :ios do

    desc "Fetch dependencies"
    lane :prepare do |options|
        build_type = options[:build_type]
        # Delete configurations in case we switch to different branch or repo
        sh "rm -rf ../Configuration"
        if build_type.nil? 
            sh "cd .. && ./setup.sh"
        else
            build = Build.new(options: options)
            # We need to update the AVS version before running setup script
            build.update_avs_version()
            sh "cd .. && ./setup.sh --override_with wire-ios-build-assets/CI\ configuration/#{build_type}"
            # Adding extra information to the icon must be done after we check them out in setup script
            build.process_icon()
        end
    end


    desc "Build for testing"
    lane :build do
        run_tests(
            scheme: "Wire-iOS",
            configuration: "Debug",
            build_for_testing: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            derived_data_path: "DerivedData",
            buildlog_path: "build",
            output_directory: "build",
            output_types: "junit"
        )
    end

    desc "Test without building"
    lane :test do
        run_tests(
            scheme: "Wire-iOS",
            configuration: "Debug",
            test_without_building: true,
            devices: ["iPhone 7"],
            code_coverage: true,
            derived_data_path: "DerivedData",
            buildlog_path: "test",
            output_directory: "test",
            output_types: "junit"
        )
    end

    desc "Build for release to AppStore or Hockey/S3"
    lane :build_for_release do |options|
        build = Build.new(options: options)

        if build.for_simulator
            Dir.chdir("..") do
                # Build the app for simulator
                sh "xcodebuild -scheme 'Wire-iOS' -configuration 'Debug' -sdk 'iphonesimulator' -derivedDataPath DerivedData -quiet clean build BUILD_NUMBER=#{build.build_number}"

                # make a "fake" .ipa package that QA will use for installing to simulator
                sh "mkdir -p debug/Payload"
                sh "mkdir -p #{build.artifact_path(with_filename: false)}"
                sh "cp -r DerivedData/Build/Products/Debug-iphonesimulator/*.app debug/Payload/"
                sh "cd debug && zip -r ../#{build.artifact_path(with_filename: true)}.ipa Payload/"
            end
        else
            build_app(
                scheme: "Wire-iOS",
                configuration: build.configuration,
                export_method: build.export_method,
                export_options: {"iCloudContainerEnvironment": "Production"},
                derived_data_path: "DerivedData",
                archive_path: build.archive_path(with_filename: true),
                buildlog_path: build.build_path,
                output_directory: build.artifact_path(with_filename: false),
                output_name: build.filename,
                include_bitcode: false,
                include_symbols: true,
                xcargs: "BUILD_NUMBER=#{build.build_number}"
            )
        end
    end

    desc "Upload to AppStore"
    lane :upload_app_store do |options|
        build = Build.new(options: options)

        sh "cp ../Configuration/Appfile ."
        deliver(
            ipa: "#{build.artifact_path(with_filename: true)}.ipa",
            submit_for_review: false,
            automatic_release: false,
            force: true, # Skip HTML report verification
            skip_binary_upload: false,
            run_precheck_before_submit: false,
            precheck_include_in_app_purchases: false,
            skip_app_version_update: true,
            skip_metadata: true,
            skip_screenshots: true,
        )
    end

    desc "Upload to S3 (Automation builds)"
    lane :upload_s3 do |options|
        build = Build.new(options: options)

        if build.appstore_build
            sh "cd ../#{build.archive_path(with_filename: false)} && tar -czf #{build.filename}.xcarchive.tgz #{build.filename}.xcarchive"
        end
        
        sh "cd .. && aws s3 cp --recursive --exclude '*'  --include '*.ipa' --include '*.xcarchive.tgz' artifacts/ s3://#{ENV['S3_BUCKET']}/ios/"
    end

    desc "Upload for internal use"
    lane :upload_hockey do |options|
        build = Build.new(options: options)
        changelog = ""

        if build.playground_build
            changelog = "Playground build for #{build.git_branch}"
        elsif build.avs_build
            changelog = "AVS #{build.avs_version}"
        elsif build.last_commit.nil? || build.last_commit.empty? 
            changelog = "No changelog available"
        else
            changelog = "Changes Since Last Build:\n" + changelog_from_git_commits(
                between: [build.last_commit, "HEAD"],
                pretty: "* [%an] %s",
            )
        end
        hockey(
          api_token: ENV["HOCKEY_APP_TOKEN"],
          public_identifier: build.hockey_app_id,
          ipa: "#{build.artifact_path(with_filename: true)}.ipa",
          notes: changelog,
          notify: "0"
        )
    end

    desc "Upload dSYMs for AppStore crash tracking"
    lane :upload_hockey_appstore do |options|
        build = Build.new(options: options)

        if !build.appstore_build
            UI.user_error! "This step is only relevant for AppStore builds"
        end

        hockey(
          api_token: ENV["HOCKEY_APP_TOKEN"],
          public_identifier: build.hockey_app_id,
          dsym: "#{build.artifact_path(with_filename: true)}.app.dSYM.zip",
          upload_dsym_only: true,
          release_type: "1",
          notify: "0"
        )
    end

    desc "Run post-test tasks"
    lane :post_test do
        sh "curl -s https://codecov.io/bash > codecov"
        sh "chmod +x codecov"
        codecov = "./codecov -J '^Wire$' -D ../DerivedData"

        if ENV["BUILD_REASON"] == "PullRequest"
            if ENV["CODECOV_TOKEN"].nil?
                UI.user_error! "codecov.io token missing for current repository. Set it in CODECOV_TOKEN environment variable"
            end

            if ENV["BUILD_SOURCEBRANCH"].nil?
                UI.user_error! "Source branch env variable missing. Set BUILD_SOURCEBRANCH to fix it"
            end

            pull_request_number = ENV["BUILD_SOURCEBRANCH"].split("/")[2] # For PRs the branch is in format "refs/pull/1/merge"

            codecov << " -t #{ENV["CODECOV_TOKEN"]} -P #{pull_request_number}"
        end

        sh codecov

    end
end

class Build
    attr_reader :build_type
    attr_reader :git_branch
    attr_reader :build_number
    attr_reader :last_commit
    attr_reader :for_simulator
    attr_reader :configuration
    attr_reader :avs_version

    def initialize(options:)
        build_number = options[:build_number]
        if build_number.nil?
            UI.user_error! "Pass build_number parameter to fastlane e.g. fastlane build build_number:1234"
        end
        build_type = options[:build_type]
        if build_type.nil? 
            UI.user_error! "Pass build_type parameter, e.g. fastlane build build_type:Development"
        end

        @last_commit = options[:last_commit]
        @build_type = build_type
        @git_branch = %x(git rev-parse --abbrev-ref HEAD).chomp
        @build_number = build_number

        for_simulator = options[:for_simulator]
        if for_simulator.nil? 
            @for_simulator = false
        else
            @for_simulator = for_simulator.to_s == 'true'
        end

        avs_version = options[:avs_version]
        if !avs_version.nil? && !avs_version.empty?
            @avs_version = avs_version
        end

        configuration = options[:configuration]
        if configuration.nil? 
            @configuration = "Release"
        else
            @configuration = configuration
        end
    end

    # Helpers

    def playground_build
        @build_type == "Playground"
    end

    def appstore_build
        @build_type == "AppStore"
    end

    def avs_build
        @build_type == "AVS"
    end

    def rc_build
        @build_type == "RC"
    end

    def debug_build
        @configuration == "Debug"
    end

    def normalized_branch_name
        @git_branch.gsub("/", "_")
    end

    def export_method
        if debug_build
            "development"
        elsif appstore_build
            "app-store"
        else 
            "enterprise"
        end
    end

    # Paths

    def artifact_path(with_filename: true)
        "artifacts/#{artifact_directory}" + (with_filename ? "/#{filename}" : "")
    end

    def build_path
        "build"
    end

    def archive_path(with_filename: true)
        # Put AppStore archive next to .ipa for futher processing
        if appstore_build
            "artifacts/#{artifact_directory}" + (with_filename ? "/#{filename}" : "")
        else 
            "#{build_path}" + (with_filename ? "/#{filename}" : "")
        end
    end

    def filename
        simulator = @for_simulator ? "-simulator" : ""
        "Wire-#{@build_type.downcase}-#{normalized_branch_name}#{simulator}-#{@build_number}"
    end

    def artifact_directory
        suffix = "" 
        if for_simulator 
            suffix = "simulator" 
        else 
            suffix = "device/" + (debug_build ? "debug" : "release")
        end

        case @build_type
        when "Playground"
            "playground-#{normalized_branch_name}/#{suffix}"
        when "Development"
            "development/#{suffix}"
        when "Internal"
            "internal/#{suffix}"
        when "AppStore"
            "release/appstore"
        when "AVS"
            "avs-experimental/#{suffix}"
        when "RC"
            "release/#{suffix}"
        else
            UI.user_error! "Unknown build type: #{@build_type}"
        end
    end

    # Force custom AVS version

    def update_avs_version
        if @avs_version.nil?
            UI.important("Using AVS version specified in source control")
        else
            %x( sed -i '' 's/^export APPSTORE_AVS_VERSION=.*/export APPSTORE_AVS_VERSION='"#{@avs_version}"'/g' ../avs-versions )
            UI.important("Using custom AVS version: #{@avs_version}")
        end
    end

    # Adding build number to icon

    def process_icon
        # No preprocessing needed for AppStore icons
        if appstore_build
            return
        end
        # Loop over all icons in the iconset
        processed = 0
        Dir.glob("../#{iconset_location}/*.png") do |image|
            width = %x( identify -format %w #{image} )
            image_height = %x( identify -format %h #{image} )
            height = Integer(image_height) / 4.0

            # Add build number to the icon
            %x( convert -background '#0008' -fill white -gravity center -size #{width}x#{height} caption:"#{extra_info}" "#{image}" +swap -gravity south -composite "#{image}" )
            processed += 1
        end
        UI.important("Proccessed #{processed} icons in #{iconset_location} by adding '#{extra_info}'")
    end

    def extra_info
        prefix = ""
        if !@avs_version.nil?
            prefix = "AVS:#{@avs_version}-"
        end
        if rc_build
            version = IO.foreach('../Wire-iOS/Resources/Configuration/Version.xcconfig').grep(/WIRE_SHORT_VERSION/).first.split(" = ")[1].chomp
            prefix = "#{version}-"
        end

        prefix + @build_number
    end

    def iconset_location
        "Configuration/Images.xcassets/AppIcon-#{iconset_name}.appiconset"
    end

    def iconset_name
        if playground_build || avs_build
            "Development"
        elsif rc_build
            "Release"
        else
            @build_type
        end
    end

    # Hockey

    def hockey_app_id
        case @build_type
        when "Playground"
            ENV["HOCKEY_IOS_PLAYGROUND_ID"]
        when "Development"
            ENV["HOCKEY_IOS_DEV_ID"]
        when "Internal"
            ENV["HOCKEY_IOS_INT_ID"]
        when "AppStore"
            ENV["HOCKEY_IOS_APPSTORE_ID"]
        when "AVS"
            ENV["HOCKEY_IOS_AVS_ID"]
        when "RC"
            ENV["HOCKEY_IOS_RELEASE_ID"]
        else
            UI.user_error! "Unknown build type: #{@build_type}"
        end
    end

end
