sources:
  - ../../Sources
templates:
  - ./LegacyAutoMockable.stencil
output:
  ./generated
args:
  autoMockableTestableImports: ["WireRequestStrategy"]
  autoMockableImports: ["WireCoreCrypto", "Combine"]
 
