#!/bin/bash
set -Eeuo pipefail

#
# Wire
# Copyright (C) 2026 Wire Swiss GmbH
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see http://www.gnu.org/licenses/.
#

#
# USAGE:
# Reads the Developer-Flags.xcconfig (the build flavour currently in place at
# wire-ios/Configuration/) and generates a Swift source file exposing its
# key/value pairs as compile-time defaults inside the WireFoundation package.
#
# The xcconfig remains the single source of truth; this script only mirrors it
# into Swift so the values are reachable from any module that links
# WireFoundation, without relying on Info.plist build-variable substitution.
#

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
REPO_ROOT="$( cd "$DIR/.." && pwd )"

XCCONFIG="$REPO_ROOT/wire-ios/Configuration/Developer-Flags.xcconfig"
OUTPUT="$REPO_ROOT/WireFoundation/Sources/WireFoundation/DeveloperFlagsDefaults.swift"

if [[ ! -f "$XCCONFIG" ]]; then
    echo "❌ Developer-Flags.xcconfig not found at $XCCONFIG"
    exit 1
fi

# Parse KEY = VALUE assignments, skipping comment (//) and blank lines.
# Inline comments (whitespace followed by //) are stripped from values.
# Output is sorted so regeneration produces a stable, churn-free diff.
ENTRIES="$(
    awk '
        /^[[:space:]]*\/\// { next }
        /^[[:space:]]*$/    { next }
        /=/ {
            key = $1
            sub(/=.*/, "", key)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)

            val = substr($0, index($0, "=") + 1)
            sub(/[[:space:]]+\/\/.*$/, "", val)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)

            # Escape for a Swift string literal.
            gsub(/\\/, "\\\\", val)
            gsub(/"/, "\\\"", val)

            if (key != "") print key "\t" val
        }
    ' "$XCCONFIG" | sort
)"

# Build the dictionary body.
DICTIONARY=""
while IFS=$'\t' read -r key value; do
    [[ -z "$key" ]] && continue
    DICTIONARY+="        \"$key\": \"$value\","$'\n'
done <<< "$ENTRIES"

cat > "$OUTPUT" <<EOF
//
// Wire
// Copyright (C) 2026 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

// Generated by scripts/generate-developer-flag-defaults.sh from
// wire-ios/Configuration/Developer-Flags.xcconfig — DO NOT EDIT.

/// Compile-time developer flag defaults, mirrored from Developer-Flags.xcconfig.
public enum DeveloperFlagsDefaults {

    /// Raw key/value pairs as declared in the xcconfig for the current build flavour.
    public static let values: [String: String] = [
$DICTIONARY    ]

    /// Returns whether the given xcconfig key is enabled (value is "1").
    public static func isEnabled(_ key: String) -> Bool {
        values[key] == "1"
    }
}
EOF

echo "✅ Generated $OUTPUT from Developer-Flags.xcconfig"
