sources:
  - ../../Source
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["LocalAuthentication", "Combine", "WireCoreCrypto"]
  autoMockableTestableImports: ["WireDataModel"]
