//
// Wire
// Copyright (C) 2026 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

import WireCallingData
import WireCallingDomain
import WireNetwork
import XCTest

@testable import WireDomain

final class MeetingCreateEventProcessorTests: XCTestCase {

    private var sut: MeetingCreateEventProcessor!
    private var repository: MeetingRepositoryProtocolMock!

    override func setUp() async throws {
        try await super.setUp()
        repository = MeetingRepositoryProtocolMock()
        sut = MeetingCreateEventProcessor(
            repository: repository
        )
    }

    override func tearDown() async throws {
        try await super.tearDown()
        repository = nil
        sut = nil
    }

    // MARK: - Tests

    func testProcessEvent_It_Pulls_Meeting_From_Repository() async throws {
        // When

        try await sut.processEvent(Scaffolding.event)

        // Then

        XCTAssertEqual(repository.pullMeetingIdQualifiedIDVoidReceivedInvocations, [Scaffolding.meetingID])
    }

    func testProcessEvent_It_Throws_When_Pulling_Meeting_Fails() async {
        // Mock

        repository.pullMeetingIdQualifiedIDVoidThrowableError = MeetingsAPIError.meetingNotFound

        // When / Then

        do {
            try await sut.processEvent(Scaffolding.event)
            XCTFail("expected an error to be thrown")
        } catch {
            XCTAssertEqual(repository.pullMeetingIdQualifiedIDVoidReceivedInvocations, [Scaffolding.meetingID])
        }
    }

    private enum Scaffolding {

        static let meetingID = WireNetwork.QualifiedID(
            id: UUID(uuidString: "99db9768-04e3-4b5d-9268-831b6a25c4ab")!,
            domain: "example.com"
        )

        static let event = MeetingCreateEvent(meetingID: meetingID)

    }

}

// duplicate symbols errors prevent using the autogenerated MeetingRepositoryProtocolMock from WireCallingDomainSupport
private final class MeetingRepositoryProtocolMock: MeetingRepositoryProtocol, @unchecked Sendable {
    typealias MeetingRecurrence = WireCallingDomain.MeetingRecurrence

    public init() {}

    //MARK: - observeMeetingChanges

    public var observeMeetingChangesAsyncStreamVoidCallsCount = 0
    public var observeMeetingChangesAsyncStreamVoidCalled: Bool {
        return observeMeetingChangesAsyncStreamVoidCallsCount > 0
    }
    public var observeMeetingChangesAsyncStreamVoidReturnValue: AsyncStream<Void>!
    public var observeMeetingChangesAsyncStreamVoidClosure: (() -> AsyncStream<Void>)?

    public func observeMeetingChanges() -> AsyncStream<Void> {
        observeMeetingChangesAsyncStreamVoidCallsCount += 1
        if let observeMeetingChangesAsyncStreamVoidClosure = observeMeetingChangesAsyncStreamVoidClosure {
            return observeMeetingChangesAsyncStreamVoidClosure()
        } else {
            return observeMeetingChangesAsyncStreamVoidReturnValue
        }
    }

    //MARK: - createMeeting

    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingThrowableError: (any Error)?
    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCallsCount = 0
    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCalled: Bool {
        return createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCallsCount > 0
    }
    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedArguments: (title: String, startTime: Date, endTime: Date, recurrence: MeetingRecurrence?)?
    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedInvocations: [(title: String, startTime: Date, endTime: Date, recurrence: MeetingRecurrence?)] = []
    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReturnValue: Meeting!
    public var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure: ((String, Date, Date, MeetingRecurrence?) async throws -> Meeting)?

    public func createMeeting(title: String, startTime: Date, endTime: Date, recurrence: MeetingRecurrence?) async throws -> Meeting {
        createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCallsCount += 1
        createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedArguments = (title: title, startTime: startTime, endTime: endTime, recurrence: recurrence)
        createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedInvocations.append((title: title, startTime: startTime, endTime: endTime, recurrence: recurrence))
        if let error = createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingThrowableError {
            throw error
        }
        if let createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure = createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure {
            return try await createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure(title, startTime, endTime, recurrence)
        } else {
            return createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReturnValue
        }
    }

    //MARK: - storeMeeting

    public var storeMeetingMeetingMeetingVoidCallsCount = 0
    public var storeMeetingMeetingMeetingVoidCalled: Bool {
        return storeMeetingMeetingMeetingVoidCallsCount > 0
    }
    public var storeMeetingMeetingMeetingVoidReceivedMeeting: (Meeting)?
    public var storeMeetingMeetingMeetingVoidReceivedInvocations: [(Meeting)] = []
    public var storeMeetingMeetingMeetingVoidClosure: ((Meeting) async -> Void)?

    public func storeMeeting(_ meeting: Meeting) async {
        storeMeetingMeetingMeetingVoidCallsCount += 1
        storeMeetingMeetingMeetingVoidReceivedMeeting = meeting
        storeMeetingMeetingMeetingVoidReceivedInvocations.append(meeting)
        await storeMeetingMeetingMeetingVoidClosure?(meeting)
    }

    //MARK: - pullMeeting

    public var pullMeetingIdQualifiedIDVoidThrowableError: (any Error)?
    public var pullMeetingIdQualifiedIDVoidCallsCount = 0
    public var pullMeetingIdQualifiedIDVoidCalled: Bool {
        return pullMeetingIdQualifiedIDVoidCallsCount > 0
    }
    public var pullMeetingIdQualifiedIDVoidReceivedId: (QualifiedID)?
    public var pullMeetingIdQualifiedIDVoidReceivedInvocations: [(QualifiedID)] = []
    public var pullMeetingIdQualifiedIDVoidClosure: ((QualifiedID) async throws -> Void)?

    public func pullMeeting(id: QualifiedID) async throws {
        pullMeetingIdQualifiedIDVoidCallsCount += 1
        pullMeetingIdQualifiedIDVoidReceivedId = id
        pullMeetingIdQualifiedIDVoidReceivedInvocations.append(id)
        if let error = pullMeetingIdQualifiedIDVoidThrowableError {
            throw error
        }
        try await pullMeetingIdQualifiedIDVoidClosure?(id)
    }

    //MARK: - pullMeetings

    public var pullMeetingsVoidThrowableError: (any Error)?
    public var pullMeetingsVoidCallsCount = 0
    public var pullMeetingsVoidCalled: Bool {
        return pullMeetingsVoidCallsCount > 0
    }
    public var pullMeetingsVoidClosure: (() async throws -> Void)?

    public func pullMeetings() async throws {
        pullMeetingsVoidCallsCount += 1
        if let error = pullMeetingsVoidThrowableError {
            throw error
        }
        try await pullMeetingsVoidClosure?()
    }

    //MARK: - deleteLocalMeeting

    public var deleteLocalMeetingIdQualifiedIDVoidCallsCount = 0
    public var deleteLocalMeetingIdQualifiedIDVoidCalled: Bool {
        return deleteLocalMeetingIdQualifiedIDVoidCallsCount > 0
    }
    public var deleteLocalMeetingIdQualifiedIDVoidReceivedId: (QualifiedID)?
    public var deleteLocalMeetingIdQualifiedIDVoidReceivedInvocations: [(QualifiedID)] = []
    public var deleteLocalMeetingIdQualifiedIDVoidClosure: ((QualifiedID) async -> Void)?

    public func deleteLocalMeeting(id: QualifiedID) async {
        deleteLocalMeetingIdQualifiedIDVoidCallsCount += 1
        deleteLocalMeetingIdQualifiedIDVoidReceivedId = id
        deleteLocalMeetingIdQualifiedIDVoidReceivedInvocations.append(id)
        await deleteLocalMeetingIdQualifiedIDVoidClosure?(id)
    }

    //MARK: - fetchMeetingsStarting

    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingThrowableError: (any Error)?
    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingCallsCount = 0
    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingCalled: Bool {
        return fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingCallsCount > 0
    }
    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingReceivedArguments: (date: Date, offset: Int, limit: Int)?
    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingReceivedInvocations: [(date: Date, offset: Int, limit: Int)] = []
    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingReturnValue: [Meeting]!
    public var fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingClosure: ((Date, Int, Int) async throws -> [Meeting])?

    public func fetchMeetingsStarting(after date: Date, offset: Int, limit: Int) async throws -> [Meeting] {
        fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingCallsCount += 1
        fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingReceivedArguments = (date: date, offset: offset, limit: limit)
        fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingReceivedInvocations.append((date: date, offset: offset, limit: limit))
        if let error = fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingThrowableError {
            throw error
        }
        if let fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingClosure = fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingClosure {
            return try await fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingClosure(date, offset, limit)
        } else {
            return fetchMeetingsStartingAfterDateDateOffsetIntLimitIntMeetingReturnValue
        }
    }

    //MARK: - hasUpcomingMeetings

    public var hasUpcomingMeetingsAfterDateDateBoolThrowableError: (any Error)?
    public var hasUpcomingMeetingsAfterDateDateBoolCallsCount = 0
    public var hasUpcomingMeetingsAfterDateDateBoolCalled: Bool {
        return hasUpcomingMeetingsAfterDateDateBoolCallsCount > 0
    }
    public var hasUpcomingMeetingsAfterDateDateBoolReceivedDate: (Date)?
    public var hasUpcomingMeetingsAfterDateDateBoolReceivedInvocations: [(Date)] = []
    public var hasUpcomingMeetingsAfterDateDateBoolReturnValue: Bool!
    public var hasUpcomingMeetingsAfterDateDateBoolClosure: ((Date) async throws -> Bool)?

    public func hasUpcomingMeetings(after date: Date) async throws -> Bool {
        hasUpcomingMeetingsAfterDateDateBoolCallsCount += 1
        hasUpcomingMeetingsAfterDateDateBoolReceivedDate = date
        hasUpcomingMeetingsAfterDateDateBoolReceivedInvocations.append(date)
        if let error = hasUpcomingMeetingsAfterDateDateBoolThrowableError {
            throw error
        }
        if let hasUpcomingMeetingsAfterDateDateBoolClosure = hasUpcomingMeetingsAfterDateDateBoolClosure {
            return try await hasUpcomingMeetingsAfterDateDateBoolClosure(date)
        } else {
            return hasUpcomingMeetingsAfterDateDateBoolReturnValue
        }
    }
}
