//
// Wire
// Copyright (C) 2026 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

import WireCallingData
import WireCallingDomain
import WireNetwork
import XCTest

@testable import WireDomain

final class MeetingDeleteEventProcessorTests: XCTestCase {

    private var sut: MeetingDeleteEventProcessor!
    private var repository: MeetingRepositoryProtocolMock!

    override func setUp() async throws {
        try await super.setUp()
        repository = MeetingRepositoryProtocolMock()
        sut = MeetingDeleteEventProcessor(
            repository: repository
        )
    }

    override func tearDown() async throws {
        try await super.tearDown()
        repository = nil
        sut = nil
    }

    // MARK: - Tests

    func testProcessEvent_It_Deletes_Local_Meeting_Via_Repository() async {
        // When

        await sut.processEvent(Scaffolding.event)

        // Then

        XCTAssertEqual(repository.deleteLocalMeetingIdQualifiedIDVoidReceivedInvocations, [Scaffolding.meetingID])
    }

    private enum Scaffolding {

        static let meetingID = WireNetwork.QualifiedID(
            id: UUID(uuidString: "99db9768-04e3-4b5d-9268-831b6a25c4ab")!,
            domain: "example.com"
        )

        static let event = MeetingDeleteEvent(meetingID: meetingID)

    }

}

// duplicate symbols errors prevent using the autogenerated MeetingRepositoryProtocolMock from WireCallingDomainSupport
private final class MeetingRepositoryProtocolMock: MeetingRepositoryProtocol, @unchecked Sendable {
    typealias MeetingRecurrence = WireCallingDomain.MeetingRecurrence

    init() {}

    //MARK: - observeMeetingChanges

    var observeMeetingChangesAsyncStreamVoidCallsCount = 0
    var observeMeetingChangesAsyncStreamVoidCalled: Bool {
        return observeMeetingChangesAsyncStreamVoidCallsCount > 0
    }
    var observeMeetingChangesAsyncStreamVoidReturnValue: AsyncStream<Void>!
    var observeMeetingChangesAsyncStreamVoidClosure: (() -> AsyncStream<Void>)?

    func observeMeetingChanges() -> AsyncStream<Void> {
        observeMeetingChangesAsyncStreamVoidCallsCount += 1
        if let observeMeetingChangesAsyncStreamVoidClosure = observeMeetingChangesAsyncStreamVoidClosure {
            return observeMeetingChangesAsyncStreamVoidClosure()
        } else {
            return observeMeetingChangesAsyncStreamVoidReturnValue
        }
    }

    //MARK: - createMeeting

    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingThrowableError: (any Error)?
    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCallsCount = 0
    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCalled: Bool {
        return createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCallsCount > 0
    }
    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedArguments: (title: String, startTime: Date, endTime: Date, recurrence: MeetingRecurrence?)?
    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedInvocations: [(title: String, startTime: Date, endTime: Date, recurrence: MeetingRecurrence?)] = []
    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReturnValue: Meeting!
    var createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure: ((String, Date, Date, MeetingRecurrence?) async throws -> Meeting)?

    func createMeeting(title: String, startTime: Date, endTime: Date, recurrence: MeetingRecurrence?) async throws -> Meeting {
        createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingCallsCount += 1
        createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedArguments = (title: title, startTime: startTime, endTime: endTime, recurrence: recurrence)
        createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReceivedInvocations.append((title: title, startTime: startTime, endTime: endTime, recurrence: recurrence))
        if let error = createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingThrowableError {
            throw error
        }
        if let createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure = createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure {
            return try await createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingClosure(title, startTime, endTime, recurrence)
        } else {
            return createMeetingTitleStringStartTimeDateEndTimeDateRecurrenceMeetingRecurrenceMeetingReturnValue
        }
    }

    //MARK: - storeMeeting

    var storeMeetingMeetingMeetingVoidCallsCount = 0
    var storeMeetingMeetingMeetingVoidCalled: Bool {
        return storeMeetingMeetingMeetingVoidCallsCount > 0
    }
    var storeMeetingMeetingMeetingVoidReceivedMeeting: (Meeting)?
    var storeMeetingMeetingMeetingVoidReceivedInvocations: [(Meeting)] = []
    var storeMeetingMeetingMeetingVoidClosure: ((Meeting) async -> Void)?

    func storeMeeting(_ meeting: Meeting) async {
        storeMeetingMeetingMeetingVoidCallsCount += 1
        storeMeetingMeetingMeetingVoidReceivedMeeting = meeting
        storeMeetingMeetingMeetingVoidReceivedInvocations.append(meeting)
        await storeMeetingMeetingMeetingVoidClosure?(meeting)
    }

    //MARK: - pullMeeting

    var pullMeetingIdQualifiedIDMeetingThrowableError: (any Error)?
    var pullMeetingIdQualifiedIDMeetingCallsCount = 0
    var pullMeetingIdQualifiedIDMeetingCalled: Bool {
        return pullMeetingIdQualifiedIDMeetingCallsCount > 0
    }
    var pullMeetingIdQualifiedIDMeetingReceivedId: (QualifiedID)?
    var pullMeetingIdQualifiedIDMeetingReceivedInvocations: [(QualifiedID)] = []
    var pullMeetingIdQualifiedIDMeetingReturnValue: Meeting?
    var pullMeetingIdQualifiedIDMeetingClosure: ((QualifiedID) async throws -> Meeting?)?

    func pullMeeting(id: QualifiedID) async throws -> Meeting? {
        pullMeetingIdQualifiedIDMeetingCallsCount += 1
        pullMeetingIdQualifiedIDMeetingReceivedId = id
        pullMeetingIdQualifiedIDMeetingReceivedInvocations.append(id)
        if let error = pullMeetingIdQualifiedIDMeetingThrowableError {
            throw error
        }
        if let pullMeetingIdQualifiedIDMeetingClosure = pullMeetingIdQualifiedIDMeetingClosure {
            return try await pullMeetingIdQualifiedIDMeetingClosure(id)
        } else {
            return pullMeetingIdQualifiedIDMeetingReturnValue
        }
    }

    //MARK: - pullMeetings

    var pullMeetingsVoidThrowableError: (any Error)?
    var pullMeetingsVoidCallsCount = 0
    var pullMeetingsVoidCalled: Bool {
        return pullMeetingsVoidCallsCount > 0
    }
    var pullMeetingsVoidClosure: (() async throws -> Void)?

    func pullMeetings() async throws {
        pullMeetingsVoidCallsCount += 1
        if let error = pullMeetingsVoidThrowableError {
            throw error
        }
        try await pullMeetingsVoidClosure?()
    }

    //MARK: - deleteLocalMeeting

    var deleteLocalMeetingIdQualifiedIDVoidCallsCount = 0
    var deleteLocalMeetingIdQualifiedIDVoidCalled: Bool {
        return deleteLocalMeetingIdQualifiedIDVoidCallsCount > 0
    }
    var deleteLocalMeetingIdQualifiedIDVoidReceivedId: (QualifiedID)?
    var deleteLocalMeetingIdQualifiedIDVoidReceivedInvocations: [(QualifiedID)] = []
    var deleteLocalMeetingIdQualifiedIDVoidClosure: ((QualifiedID) async -> Void)?

    func deleteLocalMeeting(id: QualifiedID) async {
        deleteLocalMeetingIdQualifiedIDVoidCallsCount += 1
        deleteLocalMeetingIdQualifiedIDVoidReceivedId = id
        deleteLocalMeetingIdQualifiedIDVoidReceivedInvocations.append(id)
        await deleteLocalMeetingIdQualifiedIDVoidClosure?(id)
    }

    //MARK: - deleteMeeting

    var deleteMeetingIdQualifiedIDVoidThrowableError: (any Error)?
    var deleteMeetingIdQualifiedIDVoidCallsCount = 0
    var deleteMeetingIdQualifiedIDVoidCalled: Bool {
        return deleteMeetingIdQualifiedIDVoidCallsCount > 0
    }
    var deleteMeetingIdQualifiedIDVoidReceivedId: (QualifiedID)?
    var deleteMeetingIdQualifiedIDVoidReceivedInvocations: [(QualifiedID)] = []
    var deleteMeetingIdQualifiedIDVoidClosure: ((QualifiedID) async throws -> Void)?

    func deleteMeeting(id: QualifiedID) async throws {
        deleteMeetingIdQualifiedIDVoidCallsCount += 1
        deleteMeetingIdQualifiedIDVoidReceivedId = id
        deleteMeetingIdQualifiedIDVoidReceivedInvocations.append(id)
        if let error = deleteMeetingIdQualifiedIDVoidThrowableError {
            throw error
        }
        try await deleteMeetingIdQualifiedIDVoidClosure?(id)
    }

    //MARK: - fetchMeetings

    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingThrowableError: (any Error)?
    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingCallsCount = 0
    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingCalled: Bool {
        return fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingCallsCount > 0
    }
    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingReceivedArguments: (range: Range<Date>, offset: Int, limit: Int)?
    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingReceivedInvocations: [(range: Range<Date>, offset: Int, limit: Int)] = []
    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingReturnValue: [Meeting]!
    var fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingClosure: ((Range<Date>, Int, Int) async throws -> [Meeting])?

    func fetchMeetings(in range: Range<Date>, offset: Int, limit: Int) async throws -> [Meeting] {
        fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingCallsCount += 1
        fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingReceivedArguments = (range: range, offset: offset, limit: limit)
        fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingReceivedInvocations.append((range: range, offset: offset, limit: limit))
        if let error = fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingThrowableError {
            throw error
        }
        if let fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingClosure = fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingClosure {
            return try await fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingClosure(range, offset, limit)
        } else {
            return fetchMeetingsInRangeRangeDateOffsetIntLimitIntMeetingReturnValue
        }
    }

    //MARK: - hasUpcomingMeetings

    var hasUpcomingMeetingsAfterDateDateBoolThrowableError: (any Error)?
    var hasUpcomingMeetingsAfterDateDateBoolCallsCount = 0
    var hasUpcomingMeetingsAfterDateDateBoolCalled: Bool {
        return hasUpcomingMeetingsAfterDateDateBoolCallsCount > 0
    }
    var hasUpcomingMeetingsAfterDateDateBoolReceivedDate: (Date)?
    var hasUpcomingMeetingsAfterDateDateBoolReceivedInvocations: [(Date)] = []
    var hasUpcomingMeetingsAfterDateDateBoolReturnValue: Bool!
    var hasUpcomingMeetingsAfterDateDateBoolClosure: ((Date) async throws -> Bool)?

    func hasUpcomingMeetings(after date: Date) async throws -> Bool {
        hasUpcomingMeetingsAfterDateDateBoolCallsCount += 1
        hasUpcomingMeetingsAfterDateDateBoolReceivedDate = date
        hasUpcomingMeetingsAfterDateDateBoolReceivedInvocations.append(date)
        if let error = hasUpcomingMeetingsAfterDateDateBoolThrowableError {
            throw error
        }
        if let hasUpcomingMeetingsAfterDateDateBoolClosure = hasUpcomingMeetingsAfterDateDateBoolClosure {
            return try await hasUpcomingMeetingsAfterDateDateBoolClosure(date)
        } else {
            return hasUpcomingMeetingsAfterDateDateBoolReturnValue
        }
    }

}
