//
// Wire
// Copyright (C) 2025 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

public import WireFoundation

import Foundation
import WireLogging

/// A service for tracking analytics data generated by the user.

public final class AnalyticsService: AnalyticsServiceProtocol {

    private let config: CountlyConfiguration
    private let countlyProvider: () -> any CountlyProtocol
    private var countly: (any CountlyProtocol)?
    private var currentUser: AnalyticsUser?
    private let baseSegmentation: Set<AnalyticsEvent.Segmentation>
    private let logger: WireTaggedLogger

    // MARK: - Life cycle

    /// Create a new `AnalyticsService`.
    ///
    /// A non-nil config is needed to track analytics data.

    public convenience init(
        config: CountlyConfiguration,
        deviceModel: String,
        osVersion: String,
        countlyProvider: @escaping () -> any CountlyProtocol
    ) {
        self.init(
            config: config,
            baseSegmentation: [
                .deviceModel(deviceModel),
                .osVersion(osVersion)
            ],
            countlyProvider: countlyProvider
        )
    }

    init(
        config: CountlyConfiguration,
        baseSegmentation: Set<AnalyticsEvent.Segmentation>,
        countlyProvider: @escaping () -> any CountlyProtocol
    ) {
        self.config = config
        self.baseSegmentation = baseSegmentation
        self.countlyProvider = countlyProvider
        self.logger = WireLogger.analytics
    }

    // MARK: - Enable / disable

    /// Whether tracking is currently enabled.

    public var isTrackingEnabled: Bool {
        countly != nil
    }

    public var currentDeviceID: String? {
        countly?.deviceID()
    }

    /// Start sending analytics data.

    @MainActor
    public func enableTracking() {

        logger.debug("enabling tracking")

        let countly = countlyProvider()
        self.countly = countly

        // Countly invokes UI apis so we need to run it on the main thread.
        assert(Thread.isMainThread)
        countly.start(
            appKey: config.appKey,
            host: config.host
        )

    }

    /// Stop sending analytics data.

    public func disableTracking() throws {

        logger.debug("disabling tracking")

        countly?.endSession()
        try clearCurrentUser()
        countly?.resetInstance()
        countly = nil

    }

    // MARK: - User

    /// Switch the current analytics user.
    ///
    /// - Parameter user: The user to switch to.

    public func switchUser(_ user: AnalyticsUser) throws {

        guard let countly, user != currentUser else {
            return
        }

        logger.debug("switching user")

        countly.endSession()

        try pushUser(
            user,
            mergeData: false
        )

        countly.beginSession()
    }

    /// Update the current user.
    ///
    /// If the user's id changed, all previously tracked data associated with
    /// the current id will be associated with the new id.
    ///
    /// - Parameter user: The updated current user.

    public func updateCurrentUser(_ user: AnalyticsUser) throws {
        guard
            let currentUser,
            user != currentUser
        else {
            return
        }

        logger.debug("updating current user")

        try pushUser(
            user,
            mergeData: true
        )
    }

    private func pushUser(
        _ user: AnalyticsUser?,
        mergeData: Bool
    ) throws {
        guard let countly else { return }

        if let id = user?.trackingID {
            countly.changeDeviceID(
                id.uuidString.lowercased(),
                mergeData: mergeData
            )
        }

        countly.setUserValue(
            user?.teamInfo?.id,
            forKey: AnalyticsUserKey.teamID.rawValue
        )

        countly.setUserValue(
            user?.teamInfo?.role,
            forKey: AnalyticsUserKey.teamRole.rawValue
        )

        countly.setUserValue(
            user?.teamInfo.map { String($0.size.logRound()) },
            forKey: AnalyticsUserKey.teamSize.rawValue
        )

        currentUser = user
    }

    private func clearCurrentUser() throws {
        logger.debug("clearing current user")

        try pushUser(
            nil,
            mergeData: false
        )
    }

    // MARK: - Event

    /// Track an event.
    ///
    /// - Parameter event: The event to track.

    public func trackEvent(_ event: AnalyticsEvent) {
        guard let countly, let currentUser else { return }

        var segmentation = event.segmentation.union(baseSegmentation)
        segmentation.insert(.Team.isSelfTeamMember(currentUser.teamInfo != nil))

        let rawSegmentation = Dictionary(uniqueKeysWithValues: segmentation.map {
            ($0.key, $0.value)
        })

        logger.debug("tracking event: \(event)") // TODO: what was it converted to before? CustomDebugStringConvertible?

        countly.recordEvent(
            event.name,
            segmentation: rawSegmentation
        )
    }

}

// MARK: -

private extension WireLogInterpolation {

    mutating func appendInterpolation(
        _ analyticsEvent: AnalyticsEvent
    ) {
        // no obfuscation needed
        writeText("\(analyticsEvent)")
    }

}
