#Configuration file for IOS tests
#Configure before running tests
appiumUrl=${Url}
callingServiceUrl='loadbalanced'
enableAppiumOutput=${enableAppiumOutput}
iosApplicationPath=${appPath}
oldAppPath=${oldAppPath}
realBuildNumber=${realBuildNumber}
bundleId=${bundleId}
isSimulator=${isSimulator}
UDID=${UDID}
appName=${appName}
platformVersion=${platformVersion}
driverTimeoutSeconds=${driverTimeoutSeconds}
projectBuildPath=${project.build.directory}
iOSToolsRoot=${project.build.directory}/../../tools/ios/
defaultImagesPath=${project.build.directory}/../../tools/img/
defaultAudioPath=${project.build.directory}/../../tools/audio/
defaultVideoPath=${project.build.directory}/../../tools/video/
defaultMiscResourcesPath=${project.build.directory}/../../tools/ios/misc/
defaultEmail=${defaultEmail}
defaultEmailPassword=${defaultEmailPassword}
specialEmail=${specialEmail}
specialPassword=${specialPassword}
deviceName=${deviceName}
backendType=${backendType}
perfReportPath=${perfReportPath}
isOnGrid=${isOnGrid}
browserName=${browserName}
accountPagesPath=${accountPagesPath}
kubeConfigPath=${kubeConfigPath}