//
// Wire
// Copyright (C) 2026 Wire Swiss GmbH
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see http://www.gnu.org/licenses/.
//

// Generated by scripts/generate-developer-flag-defaults.sh from
// wire-ios/Configuration/Developer-Flags.xcconfig — DO NOT EDIT.

/// Compile-time developer flag defaults, mirrored from Developer-Flags.xcconfig.
public enum DeveloperFlagsDefaults {

    /// Raw key/value pairs as declared in the xcconfig for the current build flavour.
    public static let values: [String: String] = [
        "MULTIBACKEND_ENABLED": "1",
        "WIRE_AUTHENTICATION_ENABLED": "1",
    ]

    /// Returns whether the given xcconfig key is enabled (value is "1").
    public static func isEnabled(_ key: String) -> Bool {
        values[key] == "1"
    }
}
