sources:
  - ../../Source
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["WireAnalytics", "WireFoundation"]
  autoMockableTestableImports: ["WireSyncEngine"]
