sources:
  - ../../Source
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["WireDataModel", "WireDomain", "Combine", "WireNetwork"]
  autoMockableTestableImports: ["WireSyncEngine"]
