sources:
  - ../../Source
templates:
  - ./AutoMockable.stencil
output:
  ./generated
args:
  autoMockableImports: ["WireAPI", "WireDomain", "Combine"]
  autoMockableTestableImports: ["WireSyncEngine"]
