on:
  workflow_call:
    inputs:
      folders:
        type: string
      all:
        type: boolean
        default: false
        required: false
      branch:
        type: string
        required: false
      notify_secret:
        type: string
        required: true
      test_dependencies:
        type: boolean
        default: false
      run_critical_flows:
        type: boolean
        required: true
    secrets:
      ZENKINS_USERNAME:
        required: true
      DD_API_KEY:
        required: true
      UI_TEST_LOGIN_EMAIL:
        required: true
      UI_TEST_LOGIN_PASSWORD:
        required: true
      OP_SERVICE_ACCOUNT_TOKEN:
        required: true

env: # https://docs.fastlane.tools/getting-started/ios/setup/
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  REPO_ROOT: ${{ github.workspace }}
  PACKAGES_DIR: ${{ github.workspace }}/DerivedData/CachedSwiftPackages
  UI_TEST_LOGIN_EMAIL: ${{ secrets.UI_TEST_LOGIN_EMAIL }}
  UI_TEST_LOGIN_PASSWORD: ${{ secrets.UI_TEST_LOGIN_PASSWORD }}

jobs:
  run-tests:
    name: Run tests
    runs-on: ghcr.io/cirruslabs/macos-runner:tahoe
    timeout-minutes: 90
    outputs:
      xcresult_files: ${{ steps.find-xcresults.outputs.xcresult_files }}
    env:
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_USERNAME: ${{ secrets.ZENKINS_USERNAME }}
      SLACK_WEBHOOK_URL: ${{ secrets[inputs.notify_secret] }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          lfs: 'true'

      - name: Sanitize branch name
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            BRANCH="${{ inputs.branch }}"
          elif [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "merge_group" ]; then
            BRANCH="${{ github.head_ref }}"
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          SANITIZED_BRANCH=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9._-]/_/g')
          echo "SANITIZED_BRANCH=$SANITIZED_BRANCH" | tee -a "$GITHUB_ENV"
    
      - name: Retrieve Xcode version
        run: |
          echo "XCODE_VERSION=$(cat .xcode-version)" >> $GITHUB_OUTPUT
        id: xcode-version

      - uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: ${{ steps.xcode-version.outputs.XCODE_VERSION }}

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
            path: fastlane/

      - name: Restore Carthage Cache
        uses: actions/cache@v3
        id: cache-carthage
        with:
          path: Carthage
          key: ${{ runner.os }}-xcode${{ steps.xcode-version.outputs.XCODE_VERSION }}-carthage-${{ hashFiles('Cartfile.resolved') }}

      - name: Bootstrap Carthage if no cache
        if: steps.cache-carthage.outputs.cache-hit != 'true'
        run: ./scripts/carthage.sh bootstrap --platform ios --use-xcframeworks

        # Restore Swift Package Dependencies Cache
      - name: Restore Swift Package Dependencies Cache
        id: cache-swift-packages
        uses: actions/cache@v3
        with:
          path: ${{ env.PACKAGES_DIR }}
          key: ${{ runner.os }}-swiftpm-project-${{ hashFiles('**/*.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}-false

        # Resolve Swift Package Dependencies
      - name: Resolve Swift Package Dependencies
        run: |
          ( cd $REPO_ROOT && xcodebuild -resolvePackageDependencies -disableAutomaticPackageResolution -clonedSourcePackagesDirPath "$PACKAGES_DIR" )

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Display all fastlane lanes
        if: ${{ contains(inputs.folders, 'fastlane') || inputs.all }}
        run: |
          bundle exec fastlane lanes

      - name: Setup workspace
        run: |
          ./setup.sh

      - name: Setup simulator
        run: |
          bundle exec fastlane prepare_for_tests

      - name: Install 1Password
        if: ${{ inputs.run_critical_flows }}
        uses: 1password/install-cli-action@v1

      - name: Generate env file
        if: ${{ inputs.run_critical_flows }}
        run: |
          bundle exec fastlane generate_env

      - name: "Test new critical flows"
        if: ${{ inputs.run_critical_flows }}
        run: |
          bundle exec fastlane run_uitests

      - name: "Test all selected frameworks"
        if: ${{ inputs.test_dependencies || inputs.all }}
        run: |
          bundle exec fastlane test_frameworks folders:${{ inputs.folders }} all:${{ inputs.all }}
          
      - name: "Test frameworks without dependencies"
        if: ${{ inputs.test_dependencies == false }}
        run: |
          bundle exec fastlane test_only_frameworks folders:${{ inputs.folders }}

      - name: Find all .xcresult files
        if: ${{ always() && github.event_name == 'pull_request' }}
        id: find-xcresults
        run: |
          # Find all .xcresult directories and convert them to a JSON array
          files=`find artifacts -type d -name "*.xcresult" | jq -R . | jq -s .`
          echo xcresult_files=${files} >> $GITHUB_OUTPUT
      - name: Debug Print xcresult files
        run: |
          echo "xcresult files: ${{ steps.find-xcresults.outputs.xcresult_files }}"

      - name: Upload .xcresult files as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: XCResults for ${{ env.SANITIZED_BRANCH }} (${{ github.run_id }} - ${{ github.run_attempt}})
          path: artifacts/**/*.xcresult  # Adjust this if necessary

      # Scripts
      - name: Test Scripts
        if: ${{ contains(inputs.folders, 'scripts') || inputs.all }}
        run: |
          echo "Scripts has changes"
          echo "Testing Scripts..."
          xcrun swift test --package-path ./scripts

      - name: Upload Failed snapshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Failed Snapshots and log for ${{ env.SANITIZED_BRANCH }} (${{ github.run_id }} - ${{ github.run_attempt}})
          path: |
            **/SnapshotResults/
            xcodebuild*.log

      - name: Upload Test Reports as Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test reports for ${{ env.SANITIZED_BRANCH }} (${{ github.run_id }} - ${{ github.run_attempt}})
          path: |
            build/reports/*.junit
            artifacts/**/*.junit
            app-group.zip
            fastlane/app-group.zip

      - name: Prepare visual representation of test results
        uses: EnricoMi/publish-unit-test-result-action/macos@v2
        if: always()
        with:
          files: |
            build/reports/*.junit
            artifacts/**/*.junit
          compare_to_earlier_commit: false

      - name: Archiving DerivedData Logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Derived Data Xcode for ${{env.SANITIZED_BRANCH }} (${{ github.run_id }} - ${{ github.run_attempt}})
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/**/Logs/**
            ~/Library/Logs/DiagnosticReports/**

      - name: Get Commit Info
        if: always()
        id: get_commit_sha
        run: |
            echo "commit_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
            echo "commit_message=$(git log -1 --pretty=format:"%s")" >> $GITHUB_ENV

      - name: Notify on Wire for iOS Nightly 🤖
        uses: 8398a7/action-slack@v3
        continue-on-error: true
        if: ${{ inputs.all && always() }}
        with:
          status: ${{ job.status }}
          text: |
            **Tests for ${{ env.SANITIZED_BRANCH }}**

            **Title:** ${{ env.commit_message }}
            **Commit:** [${{ env.commit_sha }}](https://github.com/wireapp/wire-ios-mono/commit/${{ env.commit_sha }})
            **Triggered by:** ${{ github.triggering_actor }}
            **Build log:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      
      - name: Notify on Wire for iOS CI
        uses: 8398a7/action-slack@v3
        continue-on-error: true
        if: ${{ !inputs.all && failure() }}
        with:
          status: ${{ job.status }}
          text: |
            **🚨 Tests for ${{ env.SANITIZED_BRANCH }} failed 🆘**

            **Title:** ${{ env.commit_message }}
            **Commit:** [${{ env.commit_sha }}](https://github.com/wireapp/wire-ios/commit/${{ env.commit_sha }})
            **Triggered by:** ${{ github.triggering_actor }}
            **Build log:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

  analyze-xcresults:
    needs: run-tests
    name: Analyze xcresults
    if: ${{ always() && github.event_name == 'pull_request' }}
    runs-on: ghcr.io/cirruslabs/macos-runner:sequoia
    strategy:
      matrix:
        xcresult_file: ${{ fromJson(needs.run-tests.outputs.xcresult_files) }}
      fail-fast: false # avoid to fail one job
    steps:
      - name: Sanitize branch name
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            BRANCH="${{ inputs.branch }}"
          elif [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "merge_group" ]; then
            BRANCH="${{ github.head_ref }}"
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          SANITIZED_BRANCH=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9._-]/_/g')
          echo "SANITIZED_BRANCH=$SANITIZED_BRANCH" >> $GITHUB_ENV

      - name: Download .xcresult files
        uses: actions/download-artifact@v4
        with:
          name: XCResults for ${{ env.SANITIZED_BRANCH }} (${{ github.run_id }} - ${{ github.run_attempt}})
          path: ./artifacts

      - name: Display downloaded files
        run: ls -R
      
      - name: Analyze .xcresult file
        uses: wireapp/analyze-xcoderesults-action@v1
        with:
          results: ${{ matrix.xcresult_file }}
          warningAnnotations: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  upload-test-results-datadadog:
    name: Upload to Datadog
    runs-on: ubuntu-24.04
    needs: run-tests
    if: always()
    steps:
      - name: Sanitize branch name
        run: |
          if [ -n "${{ inputs.branch }}" ]; then
            BRANCH="${{ inputs.branch }}"
          elif [ "${{ github.event_name }}" == "pull_request" ] || [ "${{ github.event_name }}" == "merge_group" ]; then
            BRANCH="${{ github.head_ref }}"
          else
            BRANCH="${GITHUB_REF#refs/heads/}"
          fi
          SANITIZED_BRANCH=$(echo "$BRANCH" | sed 's/[^a-zA-Z0-9._-]/_/g')
          echo "SANITIZED_BRANCH=$SANITIZED_BRANCH" >> $GITHUB_ENV

      - name: Download tests results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: Test reports for ${{ env.SANITIZED_BRANCH }} (${{ github.run_id }} - ${{ github.run_attempt}})
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install datadog-ci
        run: npm install -g @datadog/datadog-ci
      - name: "Upload results"
        env:
          DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_ENV: ci
          DATADOG_SITE: datadoghq.eu
        run: |
          find . -name "*.junit" -type f | tr '\n' ' ' | xargs -L 1 datadog-ci junit upload --service wire-ios-mono .
