on:
  workflow_call:
    inputs:
      fastlane_action:
        required: true
        type: string
      is_cloud_build:
        type: boolean
        default: true
      countly_enabled:
        type: boolean
      datadog_enabled:
        type: boolean
        default: false
      skip_security_tests:
        type: boolean
        default: true
      distribute_externals:
        type: boolean
        default: false
      produce_changelog:
        type: boolean
        default: true
      produce_debug_builds:
        type: boolean
        default: false

    secrets:
      KEYCHAIN_PASSWORD:
        required: true
      APPSTORE_API_KEY_BASE64:
        required: true
      MATCH_PASSWORD:
        required: true
      WIRE_INTERNAL_GITHUB_USER:
        required: true
      WIRE_INTERNAL_GITHUB_TOKEN:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DD_API_KEY:
        required: true
      DATADOG_APP_ID:
        required: true
      DATADOG_CLIENT_TOKEN:
        required: true
      GOV_SUBFOLDER_PRODUCTION:
        required: true
      C1_S3_SUBFOLDER_RESTRICTED:
        required: true
      C1_S3_SUBFOLDER_PRODUCTION:
        required: true
      C2_S3_SUBFOLDER_RESTRICTED:
        required: true
      C2_S3_SUBFOLDER_PRODUCTION:
        required: true
      C3_S3_SUBFOLDER_RESTRICTED:
        required: true
      C3_S3_SUBFOLDER_PRODUCTION:
        required: true
      PLAYGROUND_TESTFLIGHT_LINK:
        required: true
      BETA_TESTFLIGHT_LINK:
        required: true
      EDGE_TESTFLIGHT_LINK:
        required: true
      COUNTLY_PRODUCTION_KEY:
        required: true
      COUNTLY_INTERNAL_KEY:
        required: true
      CLIENT_NAME_C1_C2_C3:
        required: true
      CLIENT_ID_C1_C2_C3:
        required: true
      SUBMODULE_PAT:
        required: true
      JIRA_TOKEN:
        required: false
      SLACK_WEBHOOK_URL:
        required: true

env: # https://docs.fastlane.tools/getting-started/ios/setup/
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8

permissions: 
  checks: write

jobs:
  changelog:
    if: ${{ inputs.produce_changelog }}
    uses: ./.github/workflows/changelog.yml
    with:
      is_cloud_build: ${{ inputs.is_cloud_build }}
    secrets:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}

  build_and_release:
    if: always()
    timeout-minutes: 60
    needs: changelog
    runs-on: ghcr.io/cirruslabs/macos-runner:tahoe
    env:
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      MATCH_KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      APPSTORE_API_KEY_BASE64: ${{ secrets.APPSTORE_API_KEY_BASE64 }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      WIRE_INTERNAL_GITHUB_USER: ${{ secrets.WIRE_INTERNAL_GITHUB_USER }}
      WIRE_INTERNAL_GITHUB_TOKEN: ${{ secrets.WIRE_INTERNAL_GITHUB_TOKEN }}
      S3_BUCKET: "z-lohika"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
      DATADOG_API_KEY: ${{ secrets.DD_API_KEY }}
      DATADOG_APP_ID: ${{ secrets.DATADOG_APP_ID }}
      DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
      ENABLE_DATADOG: ${{ inputs.datadog_enabled }}
      GOV_SUBFOLDER_PRODUCTION: ${{ secrets.GOV_SUBFOLDER_PRODUCTION }}
      C1_S3_SUBFOLDER_RESTRICTED: ${{ secrets.C1_S3_SUBFOLDER_RESTRICTED }}
      C1_S3_SUBFOLDER_PRODUCTION: ${{ secrets.C1_S3_SUBFOLDER_PRODUCTION }}
      C2_S3_SUBFOLDER_RESTRICTED: ${{ secrets.C2_S3_SUBFOLDER_RESTRICTED }}
      C2_S3_SUBFOLDER_PRODUCTION: ${{ secrets.C2_S3_SUBFOLDER_PRODUCTION }}
      C3_S3_SUBFOLDER_RESTRICTED: ${{ secrets.C3_S3_SUBFOLDER_RESTRICTED }}
      C3_S3_SUBFOLDER_PRODUCTION: ${{ secrets.C3_S3_SUBFOLDER_PRODUCTION }}
      BETA_TESTFLIGHT_LINK: ${{ secrets.BETA_TESTFLIGHT_LINK }}
      EDGE_TESTFLIGHT_LINK: ${{ secrets.EDGE_TESTFLIGHT_LINK }}
      PLAYGROUND_TESTFLIGHT_LINK: ${{ secrets.PLAYGROUND_TESTFLIGHT_LINK }}
      COUNTLY_PRODUCTION_KEY: ${{ secrets.COUNTLY_PRODUCTION_KEY }}
      COUNTLY_INTERNAL_KEY: ${{ secrets.COUNTLY_INTERNAL_KEY }}
      ENABLE_COUNTLY: ${{ inputs.countly_enabled }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SKIP_SECURITY_TESTS: ${{ inputs.skip_security_tests }}
      SEND_TO_EXTERNALS: ${{ inputs.distribute_externals }}
      REPO_ROOT: ${{ github.workspace }}
      PACKAGES_DIR: ${{ github.workspace }}/DerivedData/CachedSwiftPackages
      DEBUG_BUILDS: ${{ inputs.produce_debug_builds == true }}

    steps:
      - name: Add Masks
        run: |
            echo "::add-mask::${{ secrets.CLIENT_NAME_C1_C2_C3 }}"
            echo "::add-mask::${{ secrets.CLIENT_ID_C1_C2_C3 }}"
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          lfs: 'false'
          token: ${{ secrets.SUBMODULE_PAT }}
          submodules: recursive
      - name: Download changelog     
        id: download_changelog
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: ${{ needs.changelog.outputs.changelog-name }}    
      - name: Setup Xcode
        id: xcode-version
        uses: ./.github/actions/setup-xcode
      - name: Restore Carthage Cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-carthage
        with:
          path: Carthage
          key: ${{ runner.os }}-xcode${{ steps.xcode-version.outputs.XCODE_VERSION }}-carthage-${{ hashFiles('Cartfile.resolved') }}
      - name: Bootstrap Carthage if no cache
        if: steps.cache-carthage.outputs.cache-hit != 'true'
        run: ./scripts/carthage.sh bootstrap --platform ios --use-xcframeworks

      - name: Cache Swift Packages
        uses: ./.github/actions/cache-swift-packages

      - name: Setup Ruby
        uses: ruby/setup-ruby@afeafc3d1ab54a631816aba4c914a0081c12ff2f # v1.310.0
        with:
          bundler-cache: true
          
      - name: Install ImageMagick
        uses: gerlero/brew-install@5e2f576b2a0ede9d50a5b08c0099c70fdda0b0b9 # v1.1.2
        with:
          packages: imagemagick ghostscript freetype

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Trigger build
        env:
          HAS_PACKAGES_CACHE_HIT: ${{ steps.cache-swift-packages.outputs.cache-hit == 'true' }}
          FASTLANE_ACTION: ${{ inputs.fastlane_action }}
        run: bundle exec fastlane "$FASTLANE_ACTION"
      - name: Check for duplicate symbol implementations
        if: always()
        continue-on-error: true
        run: ./scripts/check_duplicate_classes.sh .
      - name: Archiving Logs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: failure()
        with:
          name: build-logs (${{ github.run_id }} - ${{ github.run_attempt}})
          path: |
            /Users/runner/Library/Developer/Xcode/DerivedData/**/Logs/**
            ~/Library/Logs/DiagnosticReports/**
            build/**

      - name: Archiving env variables
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: post-build-env-${{ inputs.fastlane_action }} (${{ github.run_id }} - ${{ github.run_attempt}})
          path: |
            **/.post_build/*.env
      - name: Load .env file
        if: always()
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9 # v2.3.0
        with:
          path: fastlane/.post_build
      - uses: akiojin/decode-base64-github-action@82bef0d9c88d987dc48c45218029b8b8426b3e33 # v1.0.2
        id: base64-decoded-S3_PATHS
        with:
          base64: ${{ env.S3_PATHS }}
      - name: Notify on Wire if succeeded
        if: success()
        continue-on-error: true
        uses: ./.github/actions/notify-wire
        with:
          notify: custom
          text: |
            **${{ env.APP_NAME }}** (version: ${{ env.BUILD_VERSION }} build: ${{ env.BUILD_NUMBER }}) is ready to test 🚀
            **COUNTLY_ENABLED:** ${{ env.ENABLE_COUNTLY }}
            **DATADOG_ENABLED:** ${{ env.ENABLE_DATADOG }}
            **CHANGELOG:** ${{ needs.changelog.outputs.changelog-url }}
            **Tap on iOS device to install:** ${{ env.BUILD_INSTALL_LINK }}
            **AWS S3 Paths:**
            `${{ steps.base64-decoded-S3_PATHS.outputs.decoded }}`
            **Triggered by:** ${{ github.triggering_actor }}
            **Build log:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **SHA256:**  ${{ env.BUILD_SHA256 }}
            ${{ env.TESTFLIGHT_ERROR != '' && format('⚠️ **TestFlight:** {0}', env.TESTFLIGHT_ERROR) || '' }}
      - name: Notify on Wire if failed
        if: failure()
        continue-on-error: true
        uses: ./.github/actions/notify-wire
        with:
          notify: custom
          text: |
            🆘 Build **${{ env.APP_NAME }}** (version: ${{ env.BUILD_VERSION }} build: ${{ env.BUILD_NUMBER }}) failed 🆘
            **Triggered by:** ${{ github.triggering_actor }}
            **Build log:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            ${{ env.TESTFLIGHT_ERROR != '' && format('⚠️ **TestFlight:** {0}', env.TESTFLIGHT_ERROR) || '' }}
