name: Beta

on: [pull_request]
permissions: 
  checks: write

jobs:
  testflight_beta:
    uses: wireapp/wire-ios-mono/.github/workflows/app_release.yml@main
    with:
      fastlane_action: testflight_beta
    secrets: inherit
