name: Beta

on: [pull_request]
permissions: 
  checks: write

jobs:
  testflight_beta:
    uses: ./.github/workflows/app_release.yml
    with:
      fastlane_action: testflight_beta
    secrets: inherit
