name: Beta

on: 
  push:
    branches:
      - 'release/cycle-*' # automatically trigger a beta build when merge is done to the branch
  workflow_dispatch:
    inputs:
      distribute_externals:
        type: boolean
        description: 'Distribute externally'
        default: false
permissions: 
  checks: write

jobs:
  testflight_beta:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      countly_enabled: true
      datadog_enabled: true
      fastlane_action: testflight_beta
      distribute_externals: ${{ inputs.distribute_externals || false }}
      notify_secret: WIRE_IOS_BUILD_WEBHOOK
    secrets: inherit
