name: Beta

on: workflow_dispatch

permissions: 
  checks: write

jobs:
  testflight_beta:
    uses: ./.github/workflows/app_release.yml
    with:
      fastlane_action: testflight_beta
    secrets: inherit
