name: (CirrusCI) Beta

on: workflow_dispatch
permissions: 
  checks: write

jobs:
  testflight_beta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cirruslabs/cirrus-action@v2
        with:
          args: 'Testflight Beta'
