name: Build for PR

on:
  pull_request:
    types: [ opened, synchronize, edited, ready_for_review ]
    branches: [ 'develop' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  checks: write

jobs:
  build_develop:
    if: > # neither run for draft pr nor for changed PR title/description
      ${{ github.event.pull_request.draft != true &&
          github.event.action != 'edited' }}
    uses: ./.github/workflows/_reusable_app_release_without_changelog.yml
    with:
      countly_enabled: false
      datadog_enabled: false
      fastlane_action: development_pr
      is_cloud_build: true
      pr_s3_path: "PR-${{ github.event.pull_request.number }}"
    secrets: inherit
