name: Build for PR

on:
  pull_request:
    types: [ opened, synchronize, edited, ready_for_review ]
    branches: [ 'develop' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: 
  checks: write

jobs:
  build_develop:
    if: (github.event.action != 'edited' || (
          !contains(github.event.changes, 'title') &&
          !contains(github.event.changes, 'body') &&
          !contains(github.event.changes, 'assignees') &&
          !contains(github.event.changes, 'reviewers') &&
          !contains(github.event.changes, 'labels')
        )) && github.event.pull_request.draft == false
    uses: ./.github/workflows/_reusable_app_release_without_changelog.yml
    with:
      datadog_enabled: false
      fastlane_action: development_pr
      is_cloud_build: true
      pr_s3_path: "PR-${{ github.event.pull_request.number }}"
    secrets: inherit

