name: C1 C3 Production

on: workflow_dispatch

permissions: 
  checks: write

jobs:
  column_1_production:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_col_1_prod
      is_cloud_build: false
    secrets: inherit

  column_3_production:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_col_3_prod
      is_cloud_build: false
    secrets: inherit
