name: Critical Flows

on:
  workflow_dispatch:
    inputs:
      mac_runner:
        description: 'macOS runner'
        type: choice
        options:
          - in-house
          - cirrus
          - github
        default: in-house
  push:
    branches:
      - 'develop'
      - 'release/cycle-*'  
  
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  critical_flows:
    uses: ./.github/workflows/_reusable_run_tests.yml
    with:
      mac_runner: ${{ inputs.mac_runner || vars.DEFAULT_MAC_RUNNER || 'in-house' }}
      all: false
      notify_secret: WIRE_IOS_CRITICAL_FLOWS
      test_dependencies: false
      run_critical_flows: true
      notify: always
    secrets: inherit
