name: Edge

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'

permissions: 
  checks: write

jobs:
  development:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      countly_enabled: true
      datadog_enabled: true
      fastlane_action: development
      is_cloud_build: true
      produce_changelog: false
      distribute_externals: true # automatically deliver to Wire Employees
    secrets: inherit
