name: Gov

on:
  workflow_dispatch:
    inputs:
      datadog_enabled:
        description: 'Enable DataDog'
        type: boolean
        default: false
      skip_security_tests:
        description: 'Skip security tests'
        type: boolean
        default: false
permissions:
  checks: write

jobs:
  gov_release:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_gov
      is_cloud_build: false
      countly_enabled: false
      datadog_enabled: ${{ inputs.datadog_enabled }}
      skip_security_tests: ${{ inputs.skip_security_tests }}
      notify_secret: WIRE_IOS_BUILD_WEBHOOK
    secrets:
      # Only the secrets declared under
      # ./.github/workflows/_reusable_app_release.yml -> on.workflow_call.secrets
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      APPSTORE_API_KEY_BASE64: ${{ secrets.APPSTORE_API_KEY_BASE64 }}
      MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      WIRE_INTERNAL_GITHUB_USER: ${{ secrets.WIRE_INTERNAL_GITHUB_USER }}
      WIRE_INTERNAL_GITHUB_TOKEN: ${{ secrets.WIRE_INTERNAL_GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      DATADOG_APP_ID: ${{ secrets.DATADOG_APP_ID }}
      DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
      SUBMODULE_PAT: ${{ secrets.SUBMODULE_PAT }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
      WIRE_IOS_BUILD_WEBHOOK: ${{ secrets.WIRE_IOS_BUILD_WEBHOOK }}
      GOV_SUBFOLDER_PRODUCTION: ${{ secrets.GOV_SUBFOLDER_PRODUCTION }}
