name: Link and Lint PR with Jira Ticket Number
on:
  pull_request:
    types: [opened, edited, ready_for_review]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  add-jira-description:
    runs-on: ubuntu-24.04
    if: >
      github.event.pull_request.draft != true &&
      (github.event.action == 'opened' ||
       github.event.action == 'ready_for_review' ||
       (github.event.action == 'edited' && github.event.changes.title != null))
    steps:
      - uses: cakeinpanic/jira-description-action@c414eafc7ea6960b2a7a00442a9653543e35e5bc # v0.8.0
        name: jira-description-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://wearezeta.atlassian.net
          skip-branches: '^(production-release|main|master|release\/v\d+)$' #optional
          fail-when-jira-issue-not-found: true
