name: Playground

on:
  workflow_dispatch:
    inputs:
      distribute_externals:
        type: boolean
        description: 'Distribute externally'
        default: false

permissions: 
  checks: write

jobs:
  playground:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: playground
      distribute_externals: ${{ inputs.distribute_externals }}
    secrets: inherit
