name: Playground

on: workflow_dispatch

permissions: 
  checks: write

jobs:
  playground:
    uses: ./.github/workflows/reusable/app_release.yml
    with:
      fastlane_action: playground
    secrets: inherit
