name: Public AppStore

on: workflow_dispatch

permissions: 
  checks: write

jobs:
  public_app_release:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_public
    secrets: inherit
