name: Public AppStore

on: workflow_dispatch

permissions: 
  checks: write

jobs:
  development:
    uses: ./.github/workflows/_reusable_app_release.yml
    with:
      fastlane_action: appstore_public
    secrets: inherit
