name: Public AppStore

on: workflow_dispatch

permissions: 
  checks: write

jobs:
  development:
    uses: wireapp/wire-ios-mono/.github/workflows/app_release.yml@main
    with:
      fastlane_action: appstore_public
    secrets: inherit
