name: (CirrusCI) Public AppStore

on: workflow_dispatch
permissions: 
  checks: write

jobs:
  appstore_public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cirruslabs/cirrus-action@v2
        with:
          args: 'AppStore Public Production'
