name: Run all tests

on:
  workflow_dispatch:
    inputs:
      run_critical_flows:
        description: 'Run critical flows'
        type: boolean
        default: false

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_tests:
    uses: ./.github/workflows/_reusable_run_tests.yml
    with:
      all: true
      run_critical_flows: ${{ inputs.run_critical_flows }}
      notify: always
    secrets:
      ZENKINS_USERNAME: ${{ secrets.ZENKINS_USERNAME }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.WIRE_IOS_CI_WEBHOOK }}
