name: SwiftFormat

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:
    types: [checks_requested]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftFormat:
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.draft != true && github.event_name != 'merge_group' }}

    steps:

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            swift:
              - '**/*.swift'

      - uses: actions/checkout@v4
        if: ${{ steps.changes.outputs.swift == 'true' }}

      - name: Install SwiftFormat 0.58.3
        if: ${{ steps.changes.outputs.swift == 'true' }}
        run: |
          curl -L -o swiftformat.zip https://github.com/nicklockwood/SwiftFormat/releases/download/0.58.3/swiftformat_linux.zip
          unzip swiftformat.zip -d swiftformat_bin
          sudo mv swiftformat_bin/swiftformat_linux /usr/local/bin/swiftformat
          chmod +x /usr/local/bin/swiftformat

      - name: Run SwiftFormat
        if: ${{ steps.changes.outputs.swift == 'true' }}
        run: swiftformat --lint . --reporter github-actions-log --config .swiftformat
