name: SwiftLint

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  merge_group:
    types: [checks_requested]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftLint:
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.draft != true && github.event_name != 'merge_group' }}
    container:
      image: ghcr.io/realm/swiftlint:0.61.0

    steps:

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            swift:
              - '**/*.swift'

      - uses: actions/checkout@v4
        if: ${{ steps.changes.outputs.swift == 'true' }}

      - name: GitHub Action for SwiftLint
        if: ${{ steps.changes.outputs.swift == 'true' }}
        run: |
          swiftlint --reporter github-actions-logging --strict --quiet
