name: SwiftFormat

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]
  merge_group:
    types: [checks_requested]

# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  SwiftFormat:
    runs-on: ubuntu-24.04
    if: ${{ github.event.pull_request.draft != true }}
    container:
      image: ghcr.io/nicklockwood/swiftformat:0.54.5

    steps:
      - uses: actions/checkout@v4
      - name: GitHub Action for SwiftFormat
        run: >
          swiftformat --lint .
          --reporter github-actions-log
          --config .swiftformat
