name: Nightly Tests

on:
  workflow_dispatch:
    inputs:
      mac_runner:
        description: 'macOS runner'
        type: choice
        options:
          - in-house
          - cirrus
          - github
        default: in-house
  schedule:
    - cron: "0 21 * * MON-FRI"
  
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_tests:
    uses: ./.github/workflows/_reusable_run_tests.yml
    with:
      mac_runner: ${{ inputs.mac_runner || vars.DEFAULT_MAC_RUNNER || 'in-house' }}
      all: true
      branch: ${{ github.ref_name }}
      notify_secret: WIRE_IOS_NIGHTLY
      run_critical_flows: true
      notify: always
    secrets: inherit
