name: Test Develop

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"
  
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_tests_develop:
    uses: ./.github/workflows/_reusable_run_tests.yml
    with:
      all: true
      branch: develop
    secrets: inherit
