name: Nightly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * MON-FRI"
  
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_tests:
    if: ${{ github.ref == 'refs/heads/develop' }}
    uses: ./.github/workflows/_reusable_run_tests.yml
    with:
      all: false
      branch: develop
      notify_secret: WIRE_IOS_NIGHTLY_WEBHOOK
      run_critical_flows: true
      ui_test_tags: "!critical"
      notify: always
      timeout_minutes: 120
    secrets: inherit
