name: Nightly Tests

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * MON-FRI"
  
# This is what will cancel the workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_tests:
    strategy:
      matrix:
        branch: [develop, release/cycle-4.12, release/cycle-4.13]  # List other branches here
    uses: ./.github/workflows/_reusable_run_tests.yml
    with:
      all: true
      branch: ${{ matrix.branch }}
      notify_secret: WIRE_IOS_NIGHTLY_WEBHOOK
      run_critical_flows: true
    secrets: inherit
